
name: silk_py-devcontainer

services:

  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workspace
    environment:
      - COMPOSE_PROJECT_NAME
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../..:/workspaces:cached
    command: sleep infinity


networks:
  internal:
    driver: bridge


volumes:
  cache:
    driver: local